const hre = require("hardhat");
const ethers = hre.ethers;

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying from:", deployer.address);

  const C2Registry = await ethers.getContractFactory("C2Registry");
  const registry = await C2Registry.deploy();
  await registry.waitForDeployment();
  const address = await registry.getAddress();
  console.log("C2Registry deployed to:", address);

  // Bootstrap: register deployer as operator
  // OPERATOR_PUBKEY_HASH = sha256(server_ecdsa_pub_bytes) generated by Go server keygen
  // Until server key exists, sha256("bootstrap") is the placeholder
  const pubKeyHash =
    process.env.OPERATOR_PUBKEY_HASH ||
    ethers.sha256(ethers.toUtf8Bytes("bootstrap-placeholder"));
  await registry.registerOperator(deployer.address, pubKeyHash);
  console.log("Operator registered:", deployer.address);

  // Initial config: endpointHash = sha256(C2_SERVER_URL)
  const serverUrl = process.env.C2_SERVER_URL || "https://localhost:8443";
  const endpointHash = ethers.sha256(ethers.toUtf8Bytes(serverUrl));
  await registry.updateConfig(endpointHash, 30);
  const config = await registry.getConfig();
  console.log(
    `Config v${config.version}: endpointHash=${endpointHash} interval=30s url=${serverUrl}`
  );

  console.log("\n--- Add to .env ---");
  console.log("C2_REGISTRY_ADDRESS=" + address);
  console.log("C2_ENDPOINT_HASH=" + endpointHash);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
